---
title: "NYC DEP Harbor Water Quality Data Visualization"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: cosmo
   # logo: https://www.nature.org/content/dam/tnc/nature/en/logos/tnc-logo-white.svg
    favicon: https://www.nature.org/content/dam/tnc/nature/en/icons/general-icons/icon_nature_favicon.ico

---

```{r setup, include=FALSE}
# for adjusting font https://stackoverflow.com/questions/29274501/r-markdown-changing-font-size-and-font-type-in-html-output

library(flexdashboard)
library(sf)
library(leaflet)
library(dplyr)
library(readr)
library(ggplot2)
library(plotly)
library(crosstalk)
library(summarywidget) #from github kent37/summarywidget
library(tidyr)


sitelocs <- read_csv("../harbor_sampling_coordinates.csv") %>% 
  st_as_sf(., coords = c("Long", "Lat"), crs = 4326)


# import your data 
dat <- read_csv("../harbor_sampling_all_yrs.csv")

# convert date to a true date 
dat$date <- as.Date(as.character(dat$date), "%m/%d/%Y")
dat <-  arrange(dat, date) #%>% gather(wqvar, val, DO_top_mgL:dry_wet) Latter part makes into long form data

sd <- SharedData$new(dat, ~site)

#help("SharedData")

```

Water Quality Data
===================================== 

About {.sidebar}
-------------------------------------
#### The map represents sampling sites
Hover over a site to see the name of it

```{r}
## Create Dropdown Menu

filter_select("site", label="Site", sharedData = sd, group = ~site)

## Create Date Filter

# filter_slider("date", label = "Date Range", sharedData = sd, column = ~date)



```



Column {data-width=300}
-----------------------------------------------------------------------

### 

```{r}
leaflet(data=sitelocs) %>% 
  addTiles(urlTemplate = "https://maps{s}.nyc.gov/xyz/1.0.0/carto/basemap/{z}/{x}/{y}.jpg",
  attribution = "Map tiles courtesy of the City of New York", layerId = NULL, group = NULL,
  options = tileOptions(minZoom = 8, maxZoom = 19,  subdomains = '1234',)) %>%
  addTiles(urlTemplate = "https://maps{s}.nyc.gov/xyz/1.0.0/carto/label/{z}/{x}/{y}.png8",
  attribution = NULL, layerId = NULL, group = NULL,
  options = tileOptions(minZoom = 8, maxZoom = 19,  subdomains = '1234',)) %>%
  #addCircleMarkers(data = st_geometry(sitelocs))
  addMarkers(., label = ~as.character(Station))

```

Column {data-width=600}
-----------------------------------------------------------------------

### Chart B

```{r}
# p <- plot_ly(sd, x = ~sd[which(sd$site=="K6"),]$date, y = ~sd[which(sdt$site=="K6"),]$DO_top_mgL, type = 'scatter', mode = 'lines')
# p

p <- plot_ly(sd, x = ~date, y = ~DO_top_mgL, type = 'scatter', mode = 'lines', split = dat$site)# %>%
  #highlight(on = "plotly_click", persistent = FALSE, selectize = FALSE, opacityDim = 0.5)
p

```

### Chart C

```{r}
# p <- ggplot(sd, aes(date, val)) +
#   geom_line(aes(group = site)) +
#   #geom_smooth(data = txhousing, method = "gam") +
#   facet_wrap(~ wqvar)
#  
#  ggplotly(p, tooltip = "year") %>%
#    highlight(defaultValues = "AC1", color = "red")
```

About this work
=====================================

### Chart C

```{r}

```
